server:
  port: 8081
spring:
  data:
    mongodb:
      database: springTodos
      host: localhost
      port: 27017

auth:
  expiration: 604800
  secret: osjdhgajsbgoajsdrhbgojardsbhojarhbaorhbaksjdfhgsjdfhgsjdhsjkfhsjdkfgljshdgfksjdfghkljsdhfgvlsjdhfgvlsdhgjsdlhj
  header: Authorization